import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { getSessionUserRole } from "./lib/session";
import { headers } from 'next/headers';
import { AlertProvider } from "@/context/AlertContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Shop Management System",
  description: "Generated by create next app",
};

interface Props { role: string; children: React.ReactNode; }

export default async function RootLayout({
  children
}: Props) {
  const role = (await headers()).get('x-user-role') || '';
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AlertProvider>
          {role && <Navbar role={role} />}
          {children}
        </AlertProvider>
      </body>
    </html>
  );
}
