"use client";
import React, { useEffect, useState } from 'react';
import { ProductCard } from './ProductCard';
import Modal from '../common/Modal';
import Uploader from '../common/Uploader';
import { IProduct, IProductCSV } from '@/types/apiModels/apiModels';
import { generateUUID } from '../../../utils/common';
import Alert from '../common/Alert';
import { useAlert } from '@/context/AlertContext';

export const ProductList = () => {
    const { showAlert } = useAlert();
    const [searchTerm, setSearchTerm] = useState('');
    const [products, setProducts] = useState<IProduct[]>([]);
    const [showAddModal, setShowAddModal] = useState(false); // State for add product modal
    const [showBulkUploadModal, setShowBulkUploadModall] = useState<boolean>(false);
    const [newProduct, setNewProduct] = useState<IProduct>({
        id: '', // Assuming ID will be generated by the backend
        name: '',
        price: 0,
        description: '',
        category: '',
        image: '',
        stock: 0,
    }); // State for the new product details
    const [isLoading, setIsLoading] = useState<boolean>(false); // Loading state
    const [alertProps, setAlertProps] = useState<{
        success: boolean;
        text: string;
        duration: number;
        setVisible: (visible: boolean) => void;
    } | null>(null);
    const [alertVisible, setAlertVisible] = useState(false);
    const filteredProducts = products?.filter((product: IProduct) =>
        product.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        product.category?.toLowerCase().includes(searchTerm.toLowerCase())
    ) ?? [];

    // Fetch data from the API during build time
    async function getStaticProps() {
        setIsLoading(true); // Set loading to true before fetching
        const res = await fetch('api/product');
        const products: IProduct[] = await res.json();
        setProducts(products);
        setIsLoading(false); // Set loading to false after fetching
    }

    async function editProduct(product: IProduct) {
        try {
            const res = await fetch('/api/product', {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(product),
            });

            if (!res.ok) {
                const errorResponse = await res.json(); // Capture error response
                throw new Error(errorResponse.error || 'Failed to update product');
            }
            showAlert("Product updated ", "success");
            const updatedProducts: IProduct[] = await res.json();
            setProducts(updatedProducts);
        } catch (error) {
            console.error('Error updating product:', error);
        }
    }

    async function deletedProduct(id: string) {
        const res = await fetch(`api/product?id=` + id, {
            method: 'DELETE',
        });
        showAlert('Product deleted', "success");
        const products: IProduct[] = await res.json();
        setProducts(products);
    }

    // Function to add a new product
    const addProduct = async (newProduct: IProduct) => {
        try {
            const res = await fetch('/api/product', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(newProduct),
            });

            if (!res.ok) {
                const errorResponse = await res.json(); // Capture error response
                throw new Error(errorResponse.error || 'Failed to add product');
            }
            showAlert("Successfully products loaded", "success");
            const updatedProducts: IProduct[] = await res.json();
            setProducts(updatedProducts);
            setShowAddModal(false); // Close the modal after adding
            setNewProduct({ id: '', name: '', price: 0, description: '', category: '', image: '', stock: 0 }); // Reset new product
        } catch (error) {
            console.error('Error adding product:', error);
        }
    };

    const getParsedData = (data: IProductCSV[]): IProduct[] => {
        const today = new Date().toISOString(); // Get current date in ISO format

        return data.map((item, index) => {
            const product: IProduct = {
                id: generateUUID(), // Generate unique product id
                name: item.name || 'Unknown Product',
                image: item.image || "",
                price: item.price || 0,
                stock: item.stock || 0,
                description: item.description || "",
                category: item.category || "",
            };

            return product;
        });
    }

    const bulkUploadOrders = async (data: IProductCSV[]) => {
        debugger;
        const parsedData: IProduct[] = getParsedData(data);

        try {
            const response = await fetch("/api/product/bulk", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(parsedData),
            });
            setShowBulkUploadModall(false);
            if (!response.ok) {
                setAlertProps({
                    success: false,
                    text: "Bulk upload failed!",
                    duration: 5,
                    setVisible: setAlertVisible,
                });
                return;
            }
            const result = await response.json();
            setProducts(result);
            setShowBulkUploadModall(false);
            setAlertProps({
                success: true,
                text: "Bulk upload successfull!",
                duration: 5,
                setVisible: setAlertVisible,
            });
            console.log("Bulk Upload successfully:", result);
        } catch (error) {
            console.error("Error placing order:", error);
        }
    }

    const downloadInventory = async () => {
        const csvHeader = "ID,Name,Category,Price,Image,Stock,Description\n"; // CSV headers
        const csvRows = products.map((product) => {
            return `${product.id},${product.name},${product.category},${product.price},${product.image},${product.stock},${product.description}`;
        });

        // Combine header and rows into one string
        const csvData = csvHeader + csvRows.join("\n");

        // Create a Blob with CSV data
        const blob = new Blob([csvData], { type: 'text/csv' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = 'inventory.csv'; // File name for download

        // Programmatically click the link to trigger the download
        link.click();
    };

    useEffect(() => {
        getStaticProps();
    }, []);

    return (
        <>
            {alertVisible && alertProps && <Alert {...alertProps} />}
            <div className="container mx-auto py-8 px-8 bg-white text-black">
                {showBulkUploadModal && (
                    <Modal
                        show={showBulkUploadModal}
                        onClose={() => setShowBulkUploadModall(false)}
                    >
                        <Uploader<IProductCSV>
                            text="Upload Product Data"
                            handleUpload={bulkUploadOrders}
                        />
                    </Modal>
                )}
                <div className="flex flex-wrap items-center gap-4 mb-6">
                    {/* Search Bar */}
                    <div className="flex-grow border-black">
                        <input
                            type="text"
                            placeholder="Search products..."
                            className="w-full p-2 border rounded-md text-black h-10"
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                        />
                    </div>

                    {/* Buttons */}
                    <button
                        className="bg-green-500 text-white h-10 px-5 rounded-md hover:bg-green-600 transition duration-200"
                        onClick={() => setShowAddModal(true)}
                    >
                        Add
                    </button>

                    <button
                        className="bg-blue-800 text-white h-10 px-5 rounded-md hover:bg-green-600 transition duration-200"
                        onClick={() => setShowBulkUploadModall(true)}
                    >
                        Bulk Upload
                    </button>

                    <button
                        className="bg-green-800 text-white h-10 px-5 rounded-md hover:bg-green-600 transition duration-200"
                        onClick={() => downloadInventory()}
                    >
                        Download Inventory
                    </button>
                </div>

                {/* Fixed Height for Grid */}
                <div className="grid-container relative w-full grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6" style={{ minHeight: '400px' }}>
                    {/* Loader Spinner */}
                    {isLoading ? (
                        <div className="absolute top-0 left-0 w-full h-full flex justify-center items-center bg-gray-200 opacity-75">
                            <div className="animate-spin h-10 w-10 border-t-4 border-blue-500 rounded-full"></div>
                        </div>
                    ) : (
                        filteredProducts.map((product) => (
                            <ProductCard key={product.id} product={product} onEdit={editProduct} onDelete={deletedProduct} />
                        ))
                    )}
                </div>

                {/* Add Product Modal */}
                {showAddModal && (
                    <Modal show={showAddModal} onClose={() => { setShowAddModal(false) }}>
                        <h3 className="text-lg font-semibold mb-4 text-gray-800">Add Product</h3>
                        <form onSubmit={(e) => { e.preventDefault(); addProduct(newProduct); }} className="space-y-4">
                            <div>
                                <label className="block text-gray-700">Product Name</label>
                                <input
                                    type="text"
                                    name="name"
                                    value={newProduct.name}
                                    onChange={(e) => setNewProduct({ ...newProduct, name: e.target.value })}
                                    className="w-full p-2 border rounded text-gray-700"
                                />
                            </div>
                            <div>
                                <label className="block text-gray-700">Category</label>
                                <input
                                    type="text"
                                    name="category"
                                    value={newProduct.category}
                                    onChange={(e) => setNewProduct({ ...newProduct, category: e.target.value })}
                                    className="w-full p-2 border rounded text-gray-700"
                                />
                            </div>
                            <div>
                                <label className="block text-gray-700">Price</label>
                                <input
                                    type="number"
                                    name="price"
                                    value={newProduct.price}
                                    onChange={(e) => setNewProduct({ ...newProduct, price: Number(e.target.value) })}
                                    className="w-full p-2 border rounded text-gray-700"
                                />
                            </div>
                            <div>
                                <label className="block text-gray-700">Image URL</label>
                                <input
                                    type="text"
                                    name="image"
                                    value={newProduct.image}
                                    onChange={(e) => setNewProduct({ ...newProduct, image: e.target.value })}
                                    className="w-full p-2 border rounded text-gray-700"
                                />
                            </div>
                            <div>
                                <label className="block text-gray-700">Stock</label>
                                <input
                                    type="number"
                                    name="stock"
                                    value={newProduct.stock}
                                    onChange={(e) => setNewProduct({ ...newProduct, stock: Number(e.target.value) })}
                                    className="w-full p-2 border rounded text-gray-700"
                                />
                            </div>

                            <div className="flex justify-end space-x-4">
                                <button
                                    type="button"
                                    className="bg-gray-200 text-gray-800 py-2 px-4 rounded hover:bg-gray-300"
                                    onClick={() => setShowAddModal(false)} // Close modal without adding
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    className="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600"
                                >
                                    Add
                                </button>
                            </div>
                        </form>
                    </Modal>
                )}
            </div>
        </>
    );
};
